// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: event.proto

package grpc_event_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeEvent) Reset() {
	*x = KubeEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeEvent) ProtoMessage() {}

func (x *KubeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeEvent.ProtoReflect.Descriptor instead.
func (*KubeEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *KubeEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *KubeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KubeEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GetRecentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentEventsRequest) Reset() {
	*x = GetRecentEventsRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentEventsRequest) ProtoMessage() {}

func (x *GetRecentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*KubeEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentEventsResponse) Reset() {
	*x = GetRecentEventsResponse{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentEventsResponse) ProtoMessage() {}

func (x *GetRecentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentEventsResponse) GetEvents() []*KubeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEventsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *StreamEventsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\veventstream\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\tKubeEvent\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\".\n" +
	"\x16GetRecentEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"I\n" +
	"\x17GetRecentEventsResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.eventstream.KubeEventR\x06events\"O\n" +
	"\x13StreamEventsRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace2\xb7\x01\n" +
	"\vEventStream\x12\\\n" +
	"\x0fGetRecentEvents\x12#.eventstream.GetRecentEventsRequest\x1a$.eventstream.GetRecentEventsResponse\x12J\n" +
	"\fStreamEvents\x12 .eventstream.StreamEventsRequest\x1a\x16.eventstream.KubeEvent0\x01B*Z(go-event-dashboard/pkg/grpc-event-streamb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_proto_goTypes = []any{
	(*KubeEvent)(nil),               // 0: eventstream.KubeEvent
	(*GetRecentEventsRequest)(nil),  // 1: eventstream.GetRecentEventsRequest
	(*GetRecentEventsResponse)(nil), // 2: eventstream.GetRecentEventsResponse
	(*StreamEventsRequest)(nil),     // 3: eventstream.StreamEventsRequest
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	4, // 0: eventstream.KubeEvent.time:type_name -> google.protobuf.Timestamp
	0, // 1: eventstream.GetRecentEventsResponse.events:type_name -> eventstream.KubeEvent
	1, // 2: eventstream.EventStream.GetRecentEvents:input_type -> eventstream.GetRecentEventsRequest
	3, // 3: eventstream.EventStream.StreamEvents:input_type -> eventstream.StreamEventsRequest
	2, // 4: eventstream.EventStream.GetRecentEvents:output_type -> eventstream.GetRecentEventsResponse
	0, // 5: eventstream.EventStream.StreamEvents:output_type -> eventstream.KubeEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
